<!DOCTYPE html><html><div class="item-title">
        Item 312
      </div> <div class="item-details"><div><b>git_comments:</b> <ol></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> Fix flaky test test_operator_gpu.test_batchnorm_with_type (#11396)
                </div><div><b>message:</b> Fix flaky test test_operator_gpu.test_batchnorm_with_type (#11396)


                </div><div><b>label:</b> test
                </div></div></li></ol></div><div><b>github_issues:</b> <ol><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div><div><b>label:</b> test
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div></div></li><li><div><div><b>title:</b> Flaky test on Ubuntu: test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description
Flaky test on ubuntu_gpu for the test - test_operator_gpu.test_batchnorm_with_type. 

It is a precision error.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash:
8bf1ff1ad3e3d3f07e62043560e933848b440f57

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-9963/runs/47/nodes/486/log/?start=0

## Error Message:

&gt; FAIL: test_operator_gpu.test_batchnorm_with_type
&gt; ----------------------------------------------------------------------
&gt; Traceback (most recent call last):
&gt;   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
&gt;     self.test(*self.arg)
&gt;   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
&gt;     orig_test(*args, **kwargs)
&gt;   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 320, in test_batchnorm_with_type
&gt;     check_consistency(sym, ctx_list_v2_2D)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency
&gt;     raise e
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 1341, in check_consistency
&gt;     equal_nan=equal_nan)
&gt;   File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
&gt;     raise AssertionError(msg)
&gt; AssertionError: 
&gt; Items are not equal:
&gt; Error 1.588932 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.082301, b=0.091003
&gt;  a: array([-1308.3785    ,    -0.08230112], dtype=float32)
&gt;  b: array([-1310.   ,     0.091], dtype=float16)

## Steps to reproduce
1. Not able to reproduce locally
                </div><div><b>label:</b> test
                </div></div></li></ol></div><div><b>github_issues_comments:</b> <ol><li><div>
                Did this every used to fail before the MKL changes?
              </div></li><li><div>
                @cjolivier01 This failure was yesterday. I am not sure which MKL changes you are referring to. If you mean this - https://github.com/apache/incubator-mxnet/pull/9862 then yes, it was after the MKL changes.
              </div></li><li><div>
                For @marcoabreu do you know if this test used to fail intermittently before the MKL changes?
              </div></li><li><div>
                I have observed the problem before. https://github.com/apache/incubator-mxnet/issues/9916
It's some precision problem in batchnorm.
              </div></li><li><div>
                We are going to make the unit test stable. See here for comments and action items.
https://github.com/apache/incubator-mxnet/issues/9916#issuecomment-371736378
              </div></li><li><div>
                Great! Thanks!
              </div></li><li><div>
                Another set of failures here (2nd time in two days for two different PRs):
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11180/1/pipeline
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11157/2/pipeline/

Coming up on three months for making some improvement, so can we disable this test in the meantime?

              </div></li><li><div><div><b>body:</b> Flaky in windows:

WinPython 3: MKLDNN-GPU Win
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11186/9/pipeline

                </div><div><b>label:</b> test
                </div></div></li><li><div>
                Flakyness has not been solved: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1187/pipeline

```
======================================================================

FAIL: test_operator_gpu.test_batchnorm_with_type

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\common.py", line 175, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\test_operator_gpu.py", line 339, in test_batchnorm_with_type

    check_consistency(sym, ctx_list_v2_3D)

  File "C:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu_mkldnn\python\mxnet\test_utils.py", line 1354, in check_consistency

    raise e

  File "C:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu_mkldnn\python\mxnet\test_utils.py", line 1349, in check_consistency

    equal_nan=equal_nan)

  File "C:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu_mkldnn\python\mxnet\test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 1.114559 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=-0.217708, b=-0.370361

 a: array([-96.87876892,  -0.21770805], dtype=float32)

 b: array([-97.        ,  -0.37036133], dtype=float16)

-------------------- &gt;&gt; begin captured stdout &lt;&lt; ---------------------

Train Err: ctx 0 vs ctx 2 at norm_gamma



--------------------- &gt;&gt; end captured stdout &lt;&lt; ----------------------

-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=84210791 to reproduce.

--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------
```
              </div></li><li><div>
                Resolving via fix from @hcho3 in PR - https://github.com/apache/incubator-mxnet/pull/11873/
              </div></li></ol></div><div><b>github_pulls:</b> <ol><li><div><div><b>title:</b> [MXNET-582] Fix flaky test test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description ##
Addresses #10087. See [#9916 (comment-371736378)](https://github.com/apache/incubator-mxnet/issues/9916#issuecomment-371736378) for a justification for this change.

## Checklist ##
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)

                </div></div></li><li><div><div><b>title:</b> [MXNET-582] Fix flaky test test_operator_gpu.test_batchnorm_with_type
                </div><div><b>body:</b> ## Description ##
Addresses #10087. See [#9916 (comment-371736378)](https://github.com/apache/incubator-mxnet/issues/9916#issuecomment-371736378) for a justification for this change.

## Checklist ##
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)

                </div><div><b>label:</b> test
                </div></div></li></ol></div><div><b>github_pulls_comments:</b> <ol></ol></div><div><b>github_pulls_reviews:</b> <ol></ol></div><div><b>jira_issues:</b> <ol><li><div><div><b>summary:</b> Flaky test test_operator_gpu.test_batchnorm_with_type
                </div><div><b>description:</b> See&nbsp;https://github.com/apache/incubator-mxnet/pull/11396.
                </div></div></li></ol></div><div><b>jira_issues_comments:</b> <ol></ol></div></div></html>