<!DOCTYPE html><html><div class="item-title">
        Item 51
      </div> <div class="item-details"><div><b>git_comments:</b> <ol></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> MINOR: Add description of how consumer wakeup acts if no threads are awakened
                </div><div><b>message:</b> MINOR: Add description of how consumer wakeup acts if no threads are awakened

I think the Javadoc should describe what happens if wakeup is called and no other thread is currently blocking. This may be important in some cases, e.g. trying to shut down a poll thread, followed by manually committing offsets.

Author: Stig Rohde DÃ¸ssing &lt;sdo@it-minds.dk&gt;

Reviewers: Jason Gustafson &lt;jason@confluent.io&gt;

Closes #2093 from srdo/minor-expand-wakeup-javadoc

                </div></div></li></ol></div><div><b>github_issues:</b> <ol></ol></div><div><b>github_issues_comments:</b> <ol></ol></div><div><b>github_pulls:</b> <ol><li><div><div><b>title:</b> MINOR: Add description of how consumer wakeup acts if no threads are awakened
                </div><div><b>body:</b> I think the Javadoc should describe what happens if wakeup is called and no other thread is currently blocking. This may be important in some cases, e.g. trying to shut down a poll thread, followed by manually committing offsets.
                </div></div></li></ol></div><div><b>github_pulls_comments:</b> <ol><li><div>
                actually, this behavior looks more like a bug than intentional... @hachikuji ?

              </div></li><li><div>
                @gwenshap Actually the behavior is intentional. Usually people are expecting to receive the `WakeupException` when calling `wakeup()` (e.g. because they want to shutdown), which means there's always a race where you might accidentally call it in between calls to `poll()`. So this behavior ensures the user that they won't "miss" a wakeup call. Does that seem reasonable to you?

LGTM on the doc change itself.

              </div></li><li><div>
                LGTM. Thanks for the patch!

              </div></li></ol></div><div><b>github_pulls_reviews:</b> <ol><li><div>
                nit: Seems redundant to mention the exception twice by name in the same sentence. Maybe we can say "..., the next call to such a method will raise it instead"?

              </div></li><li><div>
                Sure, fixed

              </div></li></ol></div><div><b>jira_issues:</b> <ol></ol></div><div><b>jira_issues_comments:</b> <ol></ol></div></div></html>