<!DOCTYPE html><html><div class="item-title">
        Item 209
      </div> <div class="item-details"><div><b>git_comments:</b> <ol><li><div>
                 original cause is preserved in stack trace
              </div></li></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> [FLINK-11902][rest] Do not wrap all exceptions in RestHandlerException
                </div><div><b>message:</b> [FLINK-11902][rest] Do not wrap all exceptions in RestHandlerException

                </div></div></li></ol></div><div><b>github_issues:</b> <ol></ol></div><div><b>github_issues_comments:</b> <ol></ol></div><div><b>github_pulls:</b> <ol></ol></div><div><b>github_pulls_comments:</b> <ol></ol></div><div><b>github_pulls_reviews:</b> <ol></ol></div><div><b>jira_issues:</b> <ol><li><div><div><b>summary:</b> JarRunHandler wraps all exceptions in a RestHandlerException
                </div><div><b>description:</b> The {{JarRunHandle}} wraps every exception during the job-submission in a {{RestHandlerException}}, which should only be used for exceptions where we are aware of the underlying cause.

As a result the stacktraces from exceptions thrown during job-submission are not forwarded to users.
                </div></div></li></ol></div><div><b>jira_issues_comments:</b> <ol><li><div>
                master: f3c5dd960ff81a022ece2391ed3aee86080a352a

1.8: a3e3852973f854b7e73439856f090f22f7953f80

1.7: a35bfef06f359cb369372881016c9777ff5dbda6
              </div></li><li><div>
                Although the exception is now properly exposed in the logs it is not in the webui. iirc&nbsp;there will be a major update on the webui, will that include&nbsp;a fix for that?&nbsp;
              </div></li></ol></div></div></html>