<!DOCTYPE html><html><div class="item-title">
        Item 69
      </div> <div class="item-details"><div><b>git_comments:</b> <ol></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> LUCENE-3583: port changes from 3x
                </div><div><b>message:</b> LUCENE-3583: port changes from 3x

git-svn-id: https://svn.apache.org/repos/asf/lucene/dev/trunk@1204828 13f79535-47bb-0310-9956-ffa450edef68

                </div></div></li></ol></div><div><b>github_issues:</b> <ol></ol></div><div><b>github_issues_comments:</b> <ol></ol></div><div><b>github_pulls:</b> <ol></ol></div><div><b>github_pulls_comments:</b> <ol></ol></div><div><b>github_pulls_reviews:</b> <ol></ol></div><div><b>jira_issues:</b> <ol><li><div><div><b>summary:</b> benchmark tests always fail on windows because directory cannot be removed
                </div><div><b>description:</b> This seems to be a bug recently introduced. I have no idea what's wrong. Attached is a log file, reproduces everytime.


                </div></div></li></ol></div><div><b>jira_issues_comments:</b> <ol><li><div>
                Only fails for Lucene trunk, seems to be related to the additional cleanupo by the removal of new IndexSearcher(directory).
              </div></li><li><div>
                hudson needs a space in its folder too :)

The problem is BenchmarkTestCase, i'm sure i introduced the bug when i fixed another bug (it used TEMP_DIR directly).
              </div></li><li><div>
                OK it fails even if you have no space in the directory.

So i'm guessing this test leaves a file open (outside of mockdirectorywrapper)

We need FileSystem.setDefault(new MockWindowsFileSystem())...
              </div></li><li><div>
                It looks to me like the problem is inside LineDocSourceTest:doIndexAndSearchTest

i ran the test with -Dtestmethod=testWithDocsName, and it passes if i comment out the call to this method.
              </div></li><li><div>
                Here the complete I/O event log created by sysinternals process monitor when running test TestLineDocSource
              </div></li><li><div><div><b>body:</b> When LuceneTestCase cannot delete a file that it wants to, I'm gonna see if we can improve the output for starters.

This would make it easier to debug issues like this.
                </div><div><b>label:</b> code-design
                </div></div></li><li><div>
                with this patch the benchmark tests pass *most* of the time on my windows computer.

But sometimes they still fail (with the same filenames involved)... I have no idea why.
              </div></li><li><div>
                By the way this is the reason these tests fail now:
http://svn.apache.org/viewvc/lucene/dev/branches/lucene2621/modules/benchmark/src/test/org/apache/lucene/benchmark/BenchmarkTestCase.java?view=diff&amp;r1=1201966&amp;r2=1201967&amp;pathrev=1201967

Before they just created files underneath TEMP_DIR directly and were not closing things and were silently wrong... so the
problems have been here a while.
              </div></li><li><div>
                Setting affects 3.x, becuase i'm gonna backport my previous fix that unravelled this problem.

              </div></li><li><div>
                Patch fixes the problem in LineDocSourceTest - add tasks.close() (otherwise LDS keeps a reader open on the file).

I intend to commit shortly, after verifying all tests pass and no other such changes are required.
              </div></li><li><div>
                Committed rev 1204826 (3x).
Ported changes to trunk in rev 1204828.
              </div></li><li><div>
                I still think we should also commit Robert's patch.
              </div></li><li><div>
                You're right, I didn't notice it. I'll work on it now.
              </div></li><li><div>
                Committed Robert's changes to trunk rev 1204851. However after porting to 3x and running the tests, LineDocSourceTest consistently fails with this:

ant test -Dtestcase=LineDocSourceTest -Dtests.seed=-2895bf521e2206c:0:4f1f278a279ce441

I'm investigating (don't know if it fails on trunk too yet).
              </div></li><li><div>
                Ok found it: testInvalidFormat expected exceptions to be thrown while the algorithm runs, and so tasks.close() wasn't called. I'll change the code to close in a try-finally, for all Closeable resources.
              </div></li><li><div>
                Committed test fixes to 3x and trunk.
              </div></li><li><div>
                Shai: thanks for getting to the bottom of this!
              </div></li><li><div>
                Bulk close after release of 3.5
              </div></li></ol></div></div></html>