<!DOCTYPE html><html><div class="item-title">
        Item 200
      </div> <div class="item-details"><div><b>git_comments:</b> <ol><li><div>
                 Missing schema fields from the passed mapping
              </div></li><li><div>
                 Passed wrong schema type
              </div></li></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> ARROW-5655: [Python] Table.from_pydict/from_arrays not using types in specified schema correctly
                </div><div><b>message:</b> ARROW-5655: [Python] Table.from_pydict/from_arrays not using types in specified schema correctly

The behaviour still seems a bit inconsistent to me:
- from_arrays enforces to pass the same amount of fields as arrays
- from_pydict enables to pass a schema with a subset of mapping's fields

Both methods requires to pass a schema instance although. We could improve it by allowing to pass a list of fields or tuples, to allow the same inputs like `pa.schema` does.

cc @jorisvandenbossche @pitrou

Closes #5567 from kszucs/ARROW-5655 and squashes the following commits:

1da0547ac &lt;Krisztián Szűcs&gt; flake8
4b08c8e2e &lt;Krisztián Szűcs&gt; schema validation

Authored-by: Krisztián Szűcs &lt;szucs.krisztian@gmail.com&gt;
Signed-off-by: Wes McKinney &lt;wesm+git@apache.org&gt;

                </div></div></li></ol></div><div><b>github_issues:</b> <ol></ol></div><div><b>github_issues_comments:</b> <ol></ol></div><div><b>github_pulls:</b> <ol><li><div><div><b>title:</b> ARROW-5655: [Python] Table.from_pydict/from_arrays not using types in specified schema correctly
                </div><div><b>body:</b> The behaviour still seems a bit inconsistent to me:
- from_arrays enforces to pass the same amount of fields as arrays
- from_pydict enables to pass a schema with a subset of mapping's fields 

Both methods requires to pass a schema instance although. We could improve it by allowing to pass a list of fields or tuples, to allow the same inputs like `pa.schema` does.

cc @jorisvandenbossche @pitrou 
                </div><div><b>label:</b> code-design
                </div></div></li></ol></div><div><b>github_pulls_comments:</b> <ol><li><div>
                https://issues.apache.org/jira/browse/ARROW-5655
              </div></li><li><div><div><b>body:</b> &gt; from_arrays enforces to pass the same amount of fields as arrays

I think this is in any case to be expected, as there is otherwise no way to know which array maps to which field

&gt; from_pydict enables to pass a schema with a subset of mapping's fields

This is similar as `from_pandas`. I think both the current behaviour as raising an error on fields in the dict/dataframe that are not in the schema are decent options. I personally find the current behaviour a bit more convenient.

                </div><div><b>label:</b> code-design
                </div></div></li><li><div>
                # [Codecov](https://codecov.io/gh/apache/arrow/pull/5567?src=pr&amp;el=h1) Report
&gt; Merging [#5567](https://codecov.io/gh/apache/arrow/pull/5567?src=pr&amp;el=desc) into [master](https://codecov.io/gh/apache/arrow/commit/af097e67ac1f06aa8c9ed3f5d60d21816e820fc0?src=pr&amp;el=desc) will **decrease** coverage by `22.34%`.
&gt; The diff coverage is `87.34%`.

[![Impacted file tree graph](https://codecov.io/gh/apache/arrow/pull/5567/graphs/tree.svg?width=650&amp;token=LpTCFbqVT1&amp;height=150&amp;src=pr)](https://codecov.io/gh/apache/arrow/pull/5567?src=pr&amp;el=tree)

```diff
@@             Coverage Diff             @@
##           master    #5567       +/-   ##
===========================================
- Coverage   88.79%   66.44%   -22.35%     
===========================================
  Files         983      516      -467     
  Lines      132170    71219    -60951     
  Branches     1501        0     -1501     
===========================================
- Hits       117362    47323    -70039     
- Misses      14443    23896     +9453     
+ Partials      365        0      -365
```


| [Impacted Files](https://codecov.io/gh/apache/arrow/pull/5567?src=pr&amp;el=tree) | Coverage Δ | |
|---|---|---|
| [python/pyarrow/\_orc.pyx](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-cHl0aG9uL3B5YXJyb3cvX29yYy5weXg=) | `77.77% &lt;ø&gt; (ø)` | :arrow_up: |
| [cpp/src/arrow/filesystem/s3fs.h](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-Y3BwL3NyYy9hcnJvdy9maWxlc3lzdGVtL3MzZnMuaA==) | `100% &lt;ø&gt; (ø)` | :arrow_up: |
| [python/pyarrow/feather.pxi](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-cHl0aG9uL3B5YXJyb3cvZmVhdGhlci5weGk=) | `82.22% &lt;ø&gt; (ø)` | :arrow_up: |
| [python/pyarrow/serialization.pxi](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-cHl0aG9uL3B5YXJyb3cvc2VyaWFsaXphdGlvbi5weGk=) | `83.85% &lt;0%&gt; (ø)` | :arrow_up: |
| [python/pyarrow/\_fs.pyx](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-cHl0aG9uL3B5YXJyb3cvX2ZzLnB5eA==) | `96.82% &lt;100%&gt; (ø)` | :arrow_up: |
| [python/pyarrow/fs.py](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-cHl0aG9uL3B5YXJyb3cvZnMucHk=) | `100% &lt;100%&gt; (ø)` | :arrow_up: |
| [python/pyarrow/\_csv.pyx](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-cHl0aG9uL3B5YXJyb3cvX2Nzdi5weXg=) | `99.28% &lt;100%&gt; (ø)` | :arrow_up: |
| [python/pyarrow/s3fs.py](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-cHl0aG9uL3B5YXJyb3cvczNmcy5weQ==) | `100% &lt;100%&gt; (ø)` | :arrow_up: |
| [cpp/src/arrow/filesystem/s3fs.cc](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-Y3BwL3NyYy9hcnJvdy9maWxlc3lzdGVtL3MzZnMuY2M=) | `74.89% &lt;100%&gt; (-16.47%)` | :arrow_down: |
| [python/pyarrow/tests/test\_io.py](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree#diff-cHl0aG9uL3B5YXJyb3cvdGVzdHMvdGVzdF9pby5weQ==) | `96.98% &lt;100%&gt; (ø)` | :arrow_up: |
| ... and [737 more](https://codecov.io/gh/apache/arrow/pull/5567/diff?src=pr&amp;el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/apache/arrow/pull/5567?src=pr&amp;el=continue).
&gt; **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
&gt; `Δ = absolute &lt;relative&gt; (impact)`, `ø = not affected`, `? = missing data`
&gt; Powered by [Codecov](https://codecov.io/gh/apache/arrow/pull/5567?src=pr&amp;el=footer). Last update [af097e6...1da0547](https://codecov.io/gh/apache/arrow/pull/5567?src=pr&amp;el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

              </div></li></ol></div><div><b>github_pulls_reviews:</b> <ol><li><div>
                This is already tested below (test_table_from_pydict_schema), so maybe update the `match` check there instead
              </div></li><li><div><div><b>body:</b> It tests multiple missing keys, besides below is a parametrized test case and this is just a sanity check.
                </div><div><b>label:</b> test
                </div></div></li><li><div>
                ```suggestion
            raise TypeError('schema must be an instance of pyarrow.Schema')
```

(the argument is lower case)
              </div></li><li><div><div><b>body:</b> You can also update the other test to have 2 missing fields, or remove the other test (and move the remaining part about less fields in the schema than in the data here), if you prefer. I personally just think there is no need tin testing the exact same thing twice (our tests are already difficult enough to navigate and find what is tested where).

This is all a minor comment, though, so see what you do with it ;)
                </div><div><b>label:</b> code-design
                </div></div></li></ol></div><div><b>jira_issues:</b> <ol><li><div><div><b>summary:</b> [Python] Table.from_pydict/from_arrays not using types in specified schema correctly 
                </div><div><b>description:</b> Example with {{from_pydict}} (from https://github.com/apache/arrow/pull/4601#issuecomment-503676534):

{code:python}
In [15]: table = pa.Table.from_pydict(
    ...:     {'a': [1, 2, 3], 'b': [3, 4, 5]},
    ...:     schema=pa.schema([('a', pa.int64()), ('c', pa.int32())]))

In [16]: table
Out[16]: 
pyarrow.Table
a: int64
c: int32

In [17]: table.to_pandas()
Out[17]: 
   a  c
0  1  3
1  2  0
2  3  4
{code}

Note that the specified schema has 1) different column names and 2) has a non-default type (int32 vs int64) which leads to corrupted values.

This is partly due to {{Table.from_pydict}} not using the type information in the schema to convert the dictionary items to pyarrow arrays. But then it is also {{Table.from_arrays}} that is not correctly casting the arrays to another dtype if the schema specifies as such.

Additional question for {{Table.pydict}} is whether it actually should override the 'b' key from the dictionary as column 'c' as defined in the schema (this behaviour depends on the order of the dictionary, which is not guaranteed below python 3.6).

                </div></div></li></ol></div><div><b>jira_issues_comments:</b> <ol><li><div>
                [~kszucs] I think this might already be fixed in the mean-time. Wes and I did some work related to schema handling the last month
              </div></li><li><div>
                Issue resolved by pull request 5567
[https://github.com/apache/arrow/pull/5567]
              </div></li></ol></div></div></html>