<!DOCTYPE html><html><div class="item-title">
        Item 135
      </div> <div class="item-details"><div><b>git_comments:</b> <ol><li><div>
                 verify that the includes file contains all properties
              </div></li><li><div>
                 Add the relative path instead of the absolute one.
              </div></li><li><div>
                 Cleanup
              </div></li></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> HADOOP-17088. Failed to load XInclude files with relative path. (#2097)
                </div><div><b>message:</b> HADOOP-17088. Failed to load XInclude files with relative path. (#2097)

Contributed by Yushi Hayasaka.

Change-Id: I8aad5143c34fb831bef0077f7b659643f8ae073a

                </div></div></li></ol></div><div><b>github_issues:</b> <ol></ol></div><div><b>github_issues_comments:</b> <ol></ol></div><div><b>github_pulls:</b> <ol><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div><div><b>label:</b> code-design
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li><li><div><div><b>title:</b> HADOOP-17088. Failed to load Xinclude files with relative path in cas…
                </div><div><b>body:</b> …e of loading conf via URI

https://issues.apache.org/jira/browse/HADOOP-17088
                </div></div></li></ol></div><div><b>github_pulls_comments:</b> <ol><li><div>
                Hmm, it seems to be caused by https://issues.apache.org/jira/browse/HDFS-15424.
              </div></li><li><div>
                :confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 37s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ trunk Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  28m 57s |  trunk passed  |
| +1 :green_heart: |  compile  |  19m 32s |  trunk passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  compile  |  16m 50s |  trunk passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  checkstyle  |   1m  0s |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   1m 28s |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  16m 55s |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 40s |  trunk passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javadoc  |   1m 36s |  trunk passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +0 :ok: |  spotbugs  |   2m 16s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 14s |  trunk passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 49s |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 51s |  the patch passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javac  |  18m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 58s |  the patch passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  javac  |  16m 58s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 57s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   1m 25s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  14m 14s |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 38s |  the patch passed with JDK Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1  |
| +1 :green_heart: |  javadoc  |   1m 35s |  the patch passed with JDK Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01  |
| +1 :green_heart: |  findbugs  |   2m 19s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 27s |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 55s |  The patch does not generate ASF License warnings.  |
|  |   | 160m  5s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2097/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2097 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 3b2079663149 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / ce861836918 |
| Default Java | Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.8+10-post-Ubuntu-0ubuntu118.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2097/1/testReport/ |
| Max. process+thread count | 2156 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common U: hadoop-common-project/hadoop-common |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2097/1/console |
| versions | git=2.17.1 maven=3.6.0 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.


              </div></li><li><div>
                OK, this LGTM.

@jteagles  -can you look @ this? I plan to merge this in as is, just need your final glance at to see we haven't done anything insecure
              </div></li><li><div>
                Thanks for taking a look! JFYI, I added an example on the ticket: https://issues.apache.org/jira/browse/HADOOP-17088?focusedCommentId=17198824&amp;page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17198824
              </div></li><li><div>
                +1, merged to trunk, and I will pull back into branch-3.3, for the 3.3.1 release.
              </div></li></ol></div><div><b>github_pulls_reviews:</b> <ol><li><div>
                params are the wrong way round. not your fault, but there's no reason to replicate the existing issue.
              </div></li><li><div>
                I was worried here about what if baseFile = null at this point, but java.io.File is happy with that.

              </div></li><li><div>
                @steveloughran Thanks for the review! You mean we need to write here like that, right? (considering `expected` and `actual` order)
```java
assertEquals("b", conf.get("a"));
```
              </div></li><li><div><div><b>body:</b> exactly. Because Junit reports arg 1 as the 'expected value' in the exceptions it raises...if they are the wrong way round the error is misleading and it takes longer to debug.
                </div><div><b>label:</b> code-design
                </div></div></li><li><div>
                Thanks! Fixed.
              </div></li></ol></div><div><b>jira_issues:</b> <ol><li><div><div><b>summary:</b> Failed to load XInclude files with relative path.
                </div><div><b>description:</b> When we create a configuration file, which load a external XML file with relative path, and try to load it via calling `Configuration.addResource` with `Path(URI)`, we got an error, which failed to load a external XML, after https://issues.apache.org/jira/browse/HADOOP-14216 is merged.
{noformat}
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3021)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2973)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2848)
	at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2896)
	at com.company.test.Main.main(Main.java:29)
Caused by: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3271)
	at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3331)
	at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3114)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3007)
	... 4 more
{noformat}
The cause is that the URI is passed as string to java.io.File constructor and File does not support the file URI, so my suggestion is trying to convert from string to URI at first.
                </div></div></li><li><div><div><b>summary:</b> Failed to load XInclude files with relative path.
                </div><div><b>description:</b> When we create a configuration file, which load a external XML file with relative path, and try to load it via calling `Configuration.addResource` with `Path(URI)`, we got an error, which failed to load a external XML, after https://issues.apache.org/jira/browse/HADOOP-14216 is merged.
{noformat}
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3021)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2973)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2848)
	at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2896)
	at com.company.test.Main.main(Main.java:29)
Caused by: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3271)
	at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3331)
	at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3114)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3007)
	... 4 more
{noformat}
The cause is that the URI is passed as string to java.io.File constructor and File does not support the file URI, so my suggestion is trying to convert from string to URI at first.
                </div></div></li><li><div><div><b>summary:</b> Failed to load XInclude files with relative path.
                </div><div><b>description:</b> When we create a configuration file, which load a external XML file with relative path, and try to load it via calling `Configuration.addResource` with `Path(URI)`, we got an error, which failed to load a external XML, after https://issues.apache.org/jira/browse/HADOOP-14216 is merged.
{noformat}
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3021)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2973)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2848)
	at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2896)
	at com.company.test.Main.main(Main.java:29)
Caused by: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3271)
	at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3331)
	at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3114)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3007)
	... 4 more
{noformat}
The cause is that the URI is passed as string to java.io.File constructor and File does not support the file URI, so my suggestion is trying to convert from string to URI at first.
                </div></div></li><li><div><div><b>summary:</b> Failed to load XInclude files with relative path.
                </div><div><b>description:</b> When we create a configuration file, which load a external XML file with relative path, and try to load it via calling `Configuration.addResource` with `Path(URI)`, we got an error, which failed to load a external XML, after https://issues.apache.org/jira/browse/HADOOP-14216 is merged.
{noformat}
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3021)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2973)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2848)
	at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2896)
	at com.company.test.Main.main(Main.java:29)
Caused by: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3271)
	at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3331)
	at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3114)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3007)
	... 4 more
{noformat}
The cause is that the URI is passed as string to java.io.File constructor and File does not support the file URI, so my suggestion is trying to convert from string to URI at first.
                </div></div></li><li><div><div><b>summary:</b> Failed to load XInclude files with relative path.
                </div><div><b>description:</b> When we create a configuration file, which load a external XML file with relative path, and try to load it via calling `Configuration.addResource` with `Path(URI)`, we got an error, which failed to load a external XML, after https://issues.apache.org/jira/browse/HADOOP-14216 is merged.
{noformat}
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3021)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2973)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2848)
	at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2896)
	at com.company.test.Main.main(Main.java:29)
Caused by: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3271)
	at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3331)
	at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3114)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3007)
	... 4 more
{noformat}
The cause is that the URI is passed as string to java.io.File constructor and File does not support the file URI, so my suggestion is trying to convert from string to URI at first.
                </div></div></li><li><div><div><b>summary:</b> Failed to load XInclude files with relative path.
                </div><div><b>description:</b> When we create a configuration file, which load a external XML file with relative path, and try to load it via calling `Configuration.addResource` with `Path(URI)`, we got an error, which failed to load a external XML, after https://issues.apache.org/jira/browse/HADOOP-14216 is merged.
{noformat}
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3021)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2973)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2848)
	at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2896)
	at com.company.test.Main.main(Main.java:29)
Caused by: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3271)
	at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3331)
	at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3114)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3007)
	... 4 more
{noformat}
The cause is that the URI is passed as string to java.io.File constructor and File does not support the file URI, so my suggestion is trying to convert from string to URI at first.
                </div></div></li><li><div><div><b>summary:</b> Failed to load XInclude files with relative path.
                </div><div><b>description:</b> When we create a configuration file, which load a external XML file with relative path, and try to load it via calling `Configuration.addResource` with `Path(URI)`, we got an error, which failed to load a external XML, after https://issues.apache.org/jira/browse/HADOOP-14216 is merged.
{noformat}
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3021)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2973)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2848)
	at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2896)
	at com.company.test.Main.main(Main.java:29)
Caused by: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
	at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3271)
	at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3331)
	at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3114)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3007)
	... 4 more
{noformat}
The cause is that the URI is passed as string to java.io.File constructor and File does not support the file URI, so my suggestion is trying to convert from string to URI at first.
                </div></div></li></ol></div><div><b>jira_issues_comments:</b> <ol><li><div>
                PR: [https://github.com/apache/hadoop/pull/2097]
              </div></li><li><div>
                One important security feature is to disallow xml resources from outside of the classpath.  Does this enforce this constraint?
              </div></li><li><div>
                [~jeagles]
Thanks for the comment. But I think it is not restricted now even if the included files are provided as an absolute path (i.e. it goes without this patch) or the path of configuration file is provided as String (not URI), right?
              </div></li><li><div>
                the check for isRestricted already executes before this, so I don't see it opening up access mori
              </div></li><li><div>
                Let me add an example.
Usually, when we want to load a Hadoop configuration file, we write like that:
* Main.java
{code:java}
package com.example.test;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.Path;

import java.io.File;

public class Main {
    public static void main(String[] args) {
        String filePath = "/tmp/core-site.xml";
        File file = new File(filePath);

        Configuration configuration = new Configuration(false);
        configuration.addResource(new Path(file.toURI()));

        configuration.get("test");
    }
}
{code}

* /tmp/core-site.xml
{code:xml}
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;?xml-stylesheet type="text/xsl" href="configuration.xsl"?&gt;
&lt;!--
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License. See accompanying LICENSE file.
--&gt;

&lt;!-- Put site-specific property overrides in this file. --&gt;

&lt;configuration xmlns:xi="http://www.w3.org/2001/XInclude"&gt;
  &lt;xi:include href="mountTable.xml" /&gt;
  &lt;property&gt;
    &lt;name&gt;fs.defaultFS&lt;/name&gt;
    &lt;value&gt;viewfs://clusterX&lt;/value&gt;
  &lt;/property&gt;
&lt;/configuration&gt;
{code}

* /tmp/mountTable.xml
{code:xml}
&lt;configuration&gt;
  &lt;property&gt;
    &lt;name&gt;fs.viewfs.mounttable.ClusterX.link./data&lt;/name&gt;
    &lt;value&gt;hdfs://nn1-clusterx.example.com:8020/data&lt;/value&gt;
  &lt;/property&gt;
&lt;/configuration&gt;
{code}

(I used [ViewFs Guide|https://hadoop.apache.org/docs/r3.3.0/hadoop-project-dist/hadoop-hdfs/ViewFs.html] example)

This example passes `Path` object to `addResource` parameter and the `Path` is created from `URI` through `File.toURI()`. But actually it does not work because of the error as I explain on the description of this ticket at first.
The example works well when we use `file.getPath()` (returns String) instead of `toURI`.
Also, I think there is no difference with a security point of view because we can load the XML file which is specified by `xi:include` and located outside of the classpath when we load a configuration file using `file.getPath()`.
              </div></li></ol></div></div></html>