<!DOCTYPE html><html><div class="item-title">
        Item 105
      </div> <div class="item-details"><div><b>git_comments:</b> <ol></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> CLOUDSTACK-5726: Using runtime discovered dao (in AsyncJobManagerImpl.submitAsyncJob) to persist record has a problem to locate the right DAO instance, it causes corrupted field value be stored in database. Put in a work-around fix first to always initialize record fields in all cases
                </div><div><b>message:</b> CLOUDSTACK-5726: Using runtime discovered dao (in AsyncJobManagerImpl.submitAsyncJob) to persist record has a problem to locate the right DAO instance, it causes corrupted field value be stored in database. Put in a work-around fix first to always initialize record fields in all cases

                </div><div><b>label:</b> code-design
                </div></div></li></ol></div><div><b>github_issues:</b> <ol></ol></div><div><b>github_issues_comments:</b> <ol></ol></div><div><b>github_pulls:</b> <ol></ol></div><div><b>github_pulls_comments:</b> <ol></ol></div><div><b>github_pulls_reviews:</b> <ol></ol></div><div><b>jira_issues:</b> <ol><li><div><div><b>summary:</b> [Automation] Volume attach to vm failed with error "Unable to serialize"
                </div><div><b>description:</b> Steps to reproduce 

Step 1 : Create advanced zone in KVM or vmware
Step 2 : Deploy a VM
Step 3: Create volume
Step 4 : Attache a volume to VM

Volume attachment failed with below error 

2014-01-02 13:52:46,348 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (Job-Executor-143:ctx-3e4a400f) Add job-395 into job monitoring
2014-01-02 13:52:46,349 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Job-Executor-143:ctx-3e4a400f) Executing AsyncJobVO {id:395, userId: 2, accountId: 2, in                                stanceType: Volume, instanceId: 81, cmd: org.apache.cloudstack.api.command.user.volume.AttachVolumeCmd, cmdInfo: {"response":"json","id":"f3f4d6da-38d5-4                                213-b23c-ccda5b88ad6b","sessionkey":"cF90SOlB7bNvgOzDeKXKKAWKIBI\u003d","cmdEventType":"VOLUME.ATTACH","ctxUserId":"2","virtualMachineId":"05db9c3b-b0d5-                                4866-b582-7b05bdd5a4f2","httpmethod":"GET","_":"1388701841415","ctxAccountId":"2","ctxStartEventId":"1380"}, cmdVersion: 0, status: IN_PROGRESS, processS                                tatus: 0, resultCode: 0, result: null, initMsid: 90928106758026, completeMsid: null, lastUpdated: null, lastPolled: Thu Jan 02 13:52:44 PST 2014, created                                : Thu Jan 02 13:52:25 PST 2014}
2014-01-02 13:52:46,357 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Job-Executor-85:ctx-bb07ef89) Done executing com.cloud.storage.VmWorkAttachVolume for jo                                b-396
2014-01-02 13:52:46,360 ERROR [c.c.a.ApiAsyncJobDispatcher] (Job-Executor-97:ctx-f23ddb5a) Unexpected exception while executing org.apache.cloudstack.api                                .command.user.volume.AttachVolumeCmd
com.cloud.utils.exception.CloudRuntimeException: Unable to serialize: 81
        at org.apache.cloudstack.framework.jobs.impl.JobSerializerHelper.fromObjectSerializedString(JobSerializerHelper.java:135)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl.unmarshallResultObject(AsyncJobManagerImpl.java:667)
        at com.cloud.storage.VolumeApiServiceImpl.attachVolumeToVM(VolumeApiServiceImpl.java:1115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy195.attachVolumeToVM(Unknown Source)
        at org.apache.cloudstack.api.command.user.volume.AttachVolumeCmd.execute(AttachVolumeCmd.java:123)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:161)
        at com.cloud.api.ApiAsyncJobDispatcher.runJobInContext(ApiAsyncJobDispatcher.java:109)
        at com.cloud.api.ApiAsyncJobDispatcher$1.run(ApiAsyncJobDispatcher.java:66)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:63)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:522)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2325)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2794)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
        at java.io.ObjectInputStream.&lt;init&gt;(ObjectInputStream.java:299)
        at org.apache.cloudstack.framework.jobs.impl.JobSerializerHelper.fromObjectSerializedString(JobSerializerHelper.java:129)
        ... 32 more
2014-01-02 13:52:46,364 WARN  [o.a.c.f.j.i.AsyncJobManagerImpl] (Job-Executor-143:ctx-3e4a400f) job-395 is scheduled for wakeup run, but there is no join                                ing info anymore
2014-01-02 13:52:46,364 ERROR [o.a.c.f.j.i.AsyncJobManagerImpl] (Job-Executor-143:ctx-3e4a400f) Unable to find a wakeup dispatcher from the joined job: A                                syncJobVO {id:395, userId: 2, accountId: 2, instanceType: Volume, instanceId: 81, cmd: org.apache.cloudstack.api.command.user.volume.AttachVolumeCmd, cmd                                Info: {"response":"json","id":"f3f4d6da-38d5-4213-b23c-ccda5b88ad6b","sessionkey":"cF90SOlB7bNvgOzDeKXKKAWKIBI\u003d","cmdEventType":"VOLUME.ATTACH","ctx                                UserId":"2","virtualMachineId":"05db9c3b-b0d5-4866-b582-7b05bdd5a4f2","httpmethod":"GET","_":"1388701841415","ctxAccountId":"2","ctxStartEventId":"1380"}                                , cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 90928106758026, completeMsid: null, lastUpdated: null, las                                tPolled: Thu Jan 02 13:52:44 PST 2014, created: Thu Jan 02 13:52:25 PST 2014}
2014-01-02 13:52:46,364 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Job-Executor-143:ctx-3e4a400f) Done executing org.apache.cloudstack.api.command.user.vol                                ume.AttachVolumeCmd for job-395


                </div></div></li></ol></div><div><b>jira_issues_comments:</b> <ol><li><div>
                Commit 1dc784ecdb12b0d4f402c74941afa724faf7623e in branch refs/heads/4.3 from [~kelveny]
[ https://git-wip-us.apache.org/repos/asf?p=cloudstack.git;h=1dc784e ]

CLOUDSTACK-5726: Using runtime discovered dao (in AsyncJobManagerImpl.submitAsyncJob) to persist record has a problem to locate the right DAO instance, it causes corrupted field value be stored in database. Put in a work-around fix first to always initialize record fields in all cases

              </div></li><li><div>
                Verified with latest automation result 
              </div></li></ol></div></div></html>